-- MySQL Script generated by MySQL Workbench
-- 03/30/16 19:51:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestione_magazzino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestione_magazzino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestione_magazzino` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `gestione_magazzino` ;

-- -----------------------------------------------------
-- Table `gestione_magazzino`.`articolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestione_magazzino`.`articolo` ;

CREATE TABLE IF NOT EXISTS `gestione_magazzino`.`articolo` (
  `id_articolo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `prodotto` VARCHAR(45) NOT NULL,
  `prezzo` FLOAT NOT NULL,
  PRIMARY KEY (`id_articolo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_magazzino`.`prodotto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestione_magazzino`.`prodotto` ;

CREATE TABLE IF NOT EXISTS `gestione_magazzino`.`prodotto` (
  `id_prodotto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `descrizione` VARCHAR(150) NOT NULL,
  `disponibilita` TINYINT(1) NOT NULL,
  `numero_massimo` INT NOT NULL,
  PRIMARY KEY (`id_prodotto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_magazzino`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestione_magazzino`.`categoria` ;

CREATE TABLE IF NOT EXISTS `gestione_magazzino`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_magazzino`.`fornitore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestione_magazzino`.`fornitore` ;

CREATE TABLE IF NOT EXISTS `gestione_magazzino`.`fornitore` (
  `id_fornitore` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_fornitore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_magazzino`.`magazzino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestione_magazzino`.`magazzino` ;

CREATE TABLE IF NOT EXISTS `gestione_magazzino`.`magazzino` (
  `id_magazzino` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(20) NOT NULL,
  `indirizzo` VARCHAR(45) NOT NULL,
  `citta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_magazzino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_magazzino`.`sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestione_magazzino`.`sede` ;

CREATE TABLE IF NOT EXISTS `gestione_magazzino`.`sede` (
  `id_sede` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_sede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_magazzino`.`progetto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestione_magazzino`.`progetto` ;

CREATE TABLE IF NOT EXISTS `gestione_magazzino`.`progetto` (
  `id_progetto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `budget` FLOAT NOT NULL,
  PRIMARY KEY (`id_progetto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_magazzino`.`produttore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestione_magazzino`.`produttore` ;

CREATE TABLE IF NOT EXISTS `gestione_magazzino`.`produttore` (
  `id_produttore` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `citta` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_produttore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_magazzino`.`utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestione_magazzino`.`utente` ;

CREATE TABLE IF NOT EXISTS `gestione_magazzino`.`utente` (
  `id_utente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(225) NOT NULL,
  `cognome` VARCHAR(225) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `codice_fiscale` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `tipo_utente` VARCHAR(20) NOT NULL,
  `username` VARCHAR(225) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id_utente`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
